### ISSUE TITLE
Feature request: RESTful api

### ISSUE THREAD

**Issue by scottbedard** [rainlab/user-plugin#271]
I proposing the addition of a RESTful api for registering and authenticating users. We can do this by extracting the logic out of the components into a dedicated class, and then using it from both the components and http routes.

Or, if the community is opposed to this feature, we can still extract the authentication logic to a dedicated class so it can be consumed by other plugins that provide the endpoints.

I'd be happy to do the work myself and submit a PR. If this feature is acceptable, I'll get started right away.

**Comment by daftspunk** [comment]
As discussed prior, this should be a RESTful API plugin, perhaps on that leverages existing components or can provide (or generate) PHP code. Here is an example:

```
#
# API YAML configuration
#

paths:
    /posts
        get:
            component: blogPost
            property: posts
            params:
                - pageNumber
                - postsPerPage
            config:
                noPostsMessage: "Nothing here bro"
```

This isn't something that should concern the individual plugins.
