### ISSUE TITLE
Bug: Content Field not working with Tab Groups in Tailor

### ISSUE THREAD

**Issue by renickbuettner** [rainlab/user-plugin#585]
Hey there,

thanks for adding the Tailor support :-)

I just noticed, that it doesn't pass the "tab" property properly. So it's always in the "Content" tab, even when I set something else.

Tailor example:

```yaml
    access_users:
        label: Benutzerkonten
        comment: Benutzerkonten, die Zugriff auf diesen Eintrag haben.
        type: users
        maxItems: 0
        displayMode: controller
        translatable: false
        span: row
        spanClass: col-12
        tab: Allgemein
```

Should be in tab "Allgemein" but it's always "Content".
